---
title: "CRISPR-guided multiomics unveils direct mTOR inhibition of Hippo signaling through CDCP1: Phosphoproteomics GSEA Analysis"
output:
  html_document:
    df_print: kable
  pdf_document:
    df_print: kable
---

## Setup

```{r message = FALSE}
library(tidyverse)
library(msigdbr)
library(clusterProfiler)
library(enrichplot)
library(ggnewscale)

# plot opts
knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 3.6,
  fig.retina = 1,
  dpi = 192
)

# output directory?
out_dir <- "output/"
FGSEA_NPERM <- 10000
```

```{r load_gene_sets}
# load gene MSIGdb gene sets
gene_sets <- msigdbr(category = "H")

gene_sets <- gene_sets %>%
  select(gs_name, gene_symbol) %>%
  distinct()
```

## Nutrient-fed

```{r load_nutri_data, message=FALSE}
nutri <- read_csv('data/phosphoproteomics_nutri.csv', show_col_types = FALSE)[, -1]
nutri$symbol <- str_split(nutri$Phospho_Site, " ", simplify=TRUE)[, 1]

# drop small number of entries with missing p-values
nutri <- nutri[complete.cases(nutri), ]

dim(nutri)

# compute condition-specific totals 
nutri_rap <- nutri %>%
  select(starts_with("Rap")) %>%
  rowSums()

nutri_ric <- nutri %>%
  select(starts_with("Ric")) %>%
  rowSums()

nutri_m7 <- nutri %>%
  select(starts_with("m7")) %>%
  rowSums()

nutri_control <- nutri %>%
  select(starts_with("control")) %>%
  rowSums()

# compute knockout vs. control ratios
nutri$Ratio_Rap_v_Control <- nutri_rap / nutri_control
nutri$Ratio_Ric_v_Control <- nutri_ric / nutri_control
nutri$Ratio_m7_v_Control <- nutri_m7 / nutri_control

dim(nutri)
```

```{r}
# preview data
nutri[1:5, 1:5]
```

```{r create_gene_lists_nutri}
# construct gene score vectors for GSEA analysis;
# in cases where multiple phospho sites or proteins map to the same gene, keep the
# ratio with the largest absolute deviance from "0"
mtorc1_nutri_genes <- nutri %>%
  select(symbol, ratio = Ratio_Rap_v_Control) %>%
  mutate(log2ratio = log2(ratio)) %>%
  mutate(log2ratio_abs = abs(log2ratio)) %>%
  group_by(symbol) %>%
  arrange(-log2ratio_abs) %>%
  slice(1) %>%
  ungroup() %>%
  select(symbol, log2ratio) %>%
  arrange(-log2ratio) %>%
  deframe()

mtorc2_nutri_genes <- nutri %>%
  select(symbol, ratio = Ratio_Ric_v_Control) %>%
  mutate(log2ratio = log2(ratio)) %>%
  mutate(log2ratio_abs = abs(log2ratio)) %>%
  group_by(symbol) %>%
  arrange(-log2ratio_abs) %>%
  slice(1) %>%
  ungroup() %>%
  select(symbol, log2ratio) %>%
  arrange(-log2ratio) %>%
  deframe()

mtorc3_nutri_genes <- nutri %>%
  select(symbol, ratio = Ratio_m7_v_Control) %>%
  mutate(log2ratio = log2(ratio)) %>%
  mutate(log2ratio_abs = abs(log2ratio)) %>%
  group_by(symbol) %>%
  arrange(-log2ratio_abs) %>%
  slice(1) %>%
  ungroup() %>%
  select(symbol, log2ratio) %>%
  arrange(-log2ratio) %>%
  deframe()
```

```{r}
head(enframe(mtorc1_nutri_genes))
head(enframe(mtorc2_nutri_genes))
head(enframe(mtorc3_nutri_genes))
```

```{r fgsea, message = FALSE, warning = FALSE}
mtorc1_nutri_res <- GSEA(mtorc1_nutri_genes, TERM2GENE = gene_sets, seed = 321, pvalueCutoff = 0.15, nPermSimple = FGSEA_NPERM)
mtorc2_nutri_res <- GSEA(mtorc2_nutri_genes, TERM2GENE = gene_sets, seed = 321, pvalueCutoff = 0.15, nPermSimple = FGSEA_NPERM)
mtorc3_nutri_res <- GSEA(mtorc3_nutri_genes, TERM2GENE = gene_sets, seed = 321, pvalueCutoff = 0.15, nPermSimple = FGSEA_NPERM)
```

```{r mtorc1_results}
if (nrow(mtorc1_nutri_res@result) > 0) {
  mtorc1_nutri_res@result %>%
    select(setSize, NES, pvalue, p.adjust)

  dotplot(mtorc1_nutri_res) +
    ggplot2::xlim(0, 1.1)
} else {
  print("No significant enrichment results.") 
}
```

```{r mtorc2_nutri_results}
if (nrow(mtorc2_nutri_res@result) > 0) {
  mtorc2_nutri_res@result %>%
    select(setSize, NES, pvalue, p.adjust)

  dotplot(mtorc2_nutri_res) +
    ggplot2::xlim(0, 1.1)
} else {
  print("No significant enrichment results.") 
}
```

```{r mtorc3_nutri_results}
if (nrow(mtorc3_nutri_res@result) > 0) {
  mtorc3_nutri_res@result %>%
    select(setSize, NES, pvalue, p.adjust)

  dotplot(mtorc3_nutri_res) +
    ggplot2::xlim(0, 1.1)
} else {
  print("No significant enrichment results.") 
}
```

## Starved

```{r load_starved_data, message=FALSE}
starved <- read_csv('data/phosphoproteomics_starved.csv', show_col_types = FALSE)[, -1]
starved$symbol <- str_split(starved$Phospho_Site, " ", simplify=TRUE)[, 1]
dim(starved)

# drop few genes with missing p-values
starved <- starved[complete.cases(starved), ]
dim(starved)

# compute condition-specific totals 
starved_rap <- starved %>%
  select(starts_with("Rap")) %>%
  rowSums()

starved_ric <- starved %>%
  select(starts_with("Ric")) %>%
  rowSums()

starved_m7 <- starved %>%
  select(starts_with("m7")) %>%
  rowSums()

starved_control <- starved %>%
  select(starts_with("control")) %>%
  rowSums()

# compute knockout vs. control ratios
starved$Ratio_Rap_v_Control <- starved_rap / starved_control
starved$Ratio_Ric_v_Control <- starved_ric / starved_control
starved$Ratio_m7_v_Control <- starved_m7 / starved_control
```

```{r}
# preview data
starved[1:5, 1:5]
```

```{r create_gene_lists_starved}
# construct gene score vectors for GSEA analysis;
# in cases where multiple phospho sites or proteins map to the same gene, keep the
# ratio with the largest absolute deviance from "0"
mtorc1_starved_genes <- starved %>%
  select(symbol, ratio = Ratio_Rap_v_Control) %>%
  mutate(log2ratio = log2(ratio)) %>%
  mutate(log2ratio_abs = abs(log2ratio)) %>%
  group_by(symbol) %>%
  arrange(-log2ratio_abs) %>%
  slice(1) %>%
  ungroup() %>%
  select(symbol, log2ratio) %>%
  arrange(-log2ratio) %>%
  deframe()

mtorc2_starved_genes <- starved %>%
  select(symbol, ratio = Ratio_Ric_v_Control) %>%
  mutate(log2ratio = log2(ratio)) %>%
  mutate(log2ratio_abs = abs(log2ratio)) %>%
  group_by(symbol) %>%
  arrange(-log2ratio_abs) %>%
  slice(1) %>%
  ungroup() %>%
  select(symbol, log2ratio) %>%
  arrange(-log2ratio) %>%
  deframe()

mtorc3_starved_genes <- starved %>%
  select(symbol, ratio = Ratio_m7_v_Control) %>%
  mutate(log2ratio = log2(ratio)) %>%
  mutate(log2ratio_abs = abs(log2ratio)) %>%
  group_by(symbol) %>%
  arrange(-log2ratio_abs) %>%
  slice(1) %>%
  ungroup() %>%
  select(symbol, log2ratio) %>%
  arrange(-log2ratio) %>%
  deframe()
```

```{r}
head(enframe(mtorc1_starved_genes))
head(enframe(mtorc2_starved_genes))
head(enframe(mtorc3_starved_genes))
```

```{r fgsea_starved, message = FALSE, warning = FALSE}
mtorc1_starved_res <- GSEA(mtorc1_starved_genes, TERM2GENE = gene_sets, seed = 321, pvalueCutoff = 0.15, nPermSimple = FGSEA_NPERM)
mtorc2_starved_res <- GSEA(mtorc2_starved_genes, TERM2GENE = gene_sets, seed = 321, pvalueCutoff = 0.15, nPermSimple = FGSEA_NPERM)
mtorc3_starved_res <- GSEA(mtorc3_starved_genes, TERM2GENE = gene_sets, seed = 321, pvalueCutoff = 0.15, nPermSimple = FGSEA_NPERM)
```

```{r mtorc1_starved_results}
if (nrow(mtorc1_starved_res@result) > 0) {
  mtorc1_starved_res@result %>%
    select(setSize, NES, pvalue, p.adjust)

  dotplot(mtorc1_starved_res) +
    ggplot2::xlim(0, 1.1)
} else {
  print("No significant enrichment results.") 
}
```

```{r mtorc2_starved_results}
if (nrow(mtorc2_starved_res@result) > 0) {
  mtorc2_starved_res@result %>%
    select(setSize, NES, pvalue, p.adjust)

  if (nrow(mtorc2_starved_res) > 0) {
    dotplot(mtorc2_starved_res) +
      ggplot2::xlim(0, 1.1)
  }
} else {
  print("No significant enrichment results.") 
}
```

```{r mtorc3_starved_results}
if (nrow(mtorc3_starved_res@result) > 0) {
  mtorc3_starved_res@result %>%
    select(setSize, NES, pvalue, p.adjust)

  dotplot(mtorc3_starved_res) +
    ggplot2::xlim(0, 1.1)
} else {
  print("No significant enrichment results.") 
}
```

## Save results

```{r save_results}
if (!dir.exists(out_dir)) {
  dir.create(out_dir, mode = "0755")
}

write_tsv(mtorc1_nutri_res@result, file.path(out_dir, "phosphoproteomics-gsea-results-nutri_mtorc1.tsv"))
write_tsv(mtorc2_nutri_res@result, file.path(out_dir, "phosphoproteomics-gsea-results-nutri_mtorc2.tsv"))
write_tsv(mtorc3_nutri_res@result, file.path(out_dir, "phosphoproteomics-gsea-results-nutri_mtorc3.tsv"))

write_tsv(mtorc1_starved_res@result, file.path(out_dir, "phosphoproteomics-gsea-results-starved_mtorc1.tsv"))
write_tsv(mtorc2_starved_res@result, file.path(out_dir, "phosphoproteomics-gsea-results-starved_mtorc2.tsv"))
write_tsv(mtorc3_starved_res@result, file.path(out_dir, "phosphoproteomics-gsea-results-starved_mtorc3.tsv"))
```

## Session Info

```{r}
sessionInfo()
```
